version: '3'
services:
  mysql:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root1
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user1
    ports:
      - "3306:3306"
    container_name: cont-mysql

  postgres:
    build: ./postgres
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user1
    ports:
      - "5432:5432"
    container_name: cont-postgres
